export function generateTasksForBatch(plantingDate: Date, batchId: string, farmId: string) {
  const pd = new Date(plantingDate);
  const addDays = (d: Date, days: number) => new Date(d.getTime() + days * 86400000);
  const addMonths = (d: Date, months: number) => {
    const r = new Date(d);
    r.setMonth(r.getMonth() + months);
    return r;
  };

  return [
    { title: 'H0: Pre-emergence herbicide application', description: 'Apply Pendimethalin 330EC across all inter-row areas before weed germination. Rate: 3-4 L/ha diluted in 200-300L water. Keep away from sucker base.', category: 'herbicide', dueDate: addDays(pd, 10), priority: 'high', product: 'Pendimethalin 330EC (Stomp/Pendistar)', quantity: '1.2-1.6 L per acre', farmId, batchId },
    { title: 'Apply heavy mulching around all plants', description: 'Apply 5-8cm layer of dry grass or leaves around the base of each plant. Retains moisture, suppresses weeds.', category: 'other', dueDate: addDays(pd, 14), priority: 'high', product: 'Dry grass / leaves', quantity: 'Full coverage around each plant', farmId, batchId },
    { title: 'Apply poultry manure (Month 1)', description: 'Apply 2kg poultry manure per plant around the base in a ring 30cm from stem. Compensates for missed basal NPK at planting.', category: 'fertilizer', dueDate: addMonths(pd, 1), priority: 'medium', product: 'Poultry manure', quantity: '2kg per plant', farmId, batchId },
    { title: 'Farm inspection — establishment check', description: 'Walk every row. Check establishment rate, identify dead plants, check for weevil damage, assess mulch coverage.', category: 'inspection', dueDate: addDays(pd, 45), priority: 'medium', farmId, batchId },
    { title: 'F1: First top dress — NPK 15:15:15 (Month 2.5)', description: 'Apply NPK 15:15:15 in ring application 30-40cm from each stem. Do NOT touch stem. Apply to moist soil only. 250g per plant (compensated rate).', category: 'fertilizer', dueDate: addDays(pd, 75), priority: 'high', product: 'NPK 15:15:15', quantity: '250g per plant (170kg total = 3.5 bags of 50kg)', farmId, batchId },
    { title: 'H1: Post-emergence herbicide (same week as F1)', description: 'Apply Paraquat 200SL directed spray BETWEEN rows only. Maintain 50cm+ distance from plantain stem. Manual weed within 30cm of stem.', category: 'herbicide', dueDate: addDays(pd, 77), priority: 'high', product: 'Paraquat 200SL (Gramoxone)', quantity: '2-3 L/ha directed', farmId, batchId },
    { title: 'Apply wood ash to all plants (Month 3)', description: 'Apply generous handful of wood ash from kitchen fire around each plant. Free source of potassium.', category: 'fertilizer', dueDate: addMonths(pd, 3), priority: 'low', product: 'Wood ash', quantity: 'Large handful per plant', farmId, batchId },
    { title: 'Banana weevil inspection and trapping', description: 'Set pseudo-stem traps near base (1 trap per 20-30 plants). Check daily for 1 week, kill any adult weevils found.', category: 'pest_control', dueDate: addMonths(pd, 3), priority: 'medium', farmId, batchId },
    { title: 'Sucker count and management check (Month 4)', description: 'Walk every mat. Count sword suckers. Remove all water suckers. Leave maximum 2 sword suckers per mat.', category: 'inspection', dueDate: addMonths(pd, 4), priority: 'medium', farmId, batchId },
    { title: 'F2: Pre-flowering fertilizer — NPK 12:12:17 (Month 5) — CRITICAL', description: 'SWITCH to high-potassium NPK 12:12:17. Apply in ring 40-50cm from stem. Drives flower bud formation — do not skip or delay.', category: 'fertilizer', dueDate: addMonths(pd, 5), priority: 'critical', product: 'NPK 12:12:17', quantity: '200g per plant (136kg total = 3 bags of 50kg)', farmId, batchId },
    { title: 'H2: Post-emergence herbicide (same week as F2)', description: 'Apply Paraquat 200SL directed between rows. Protect nutrient uptake from F2 application.', category: 'herbicide', dueDate: addDays(addMonths(pd, 5), 2), priority: 'high', product: 'Paraquat 200SL or 2,4-D Amine 720SL', quantity: '2-3 L/ha directed', farmId, batchId },
    { title: 'SUCKER HARVEST — collect 60-90cm sword suckers (Month 6)', description: 'Begin harvesting sword suckers that have reached 60-90cm. Leave 1 ratoon per mat. Cut with piece of mother corm attached. Replant within 24-48 hours.', category: 'sucker_harvest', dueDate: addMonths(pd, 6), priority: 'high', farmId, batchId },
    { title: 'F3: Bunch filling fertilizer — NPK 12:12:17 + MOP (Month 7) — NON-NEGOTIABLE', description: 'Most critical application. Apply NPK 12:12:17 (250g) + Muriate of Potash MOP (50g) per plant. Accounts for 40-50% of final bunch weight.', category: 'fertilizer', dueDate: addMonths(pd, 7), priority: 'critical', product: 'NPK 12:12:17 + Muriate of Potash (MOP)', quantity: '250g NPK 12:12:17 + 50g MOP per plant', farmId, batchId },
    { title: 'H3: Post-emergence herbicide (Month 7)', description: 'Apply Paraquat 200SL directed between rows same week as F3. Extra care near mats beginning to flower.', category: 'herbicide', dueDate: addDays(addMonths(pd, 7), 2), priority: 'high', product: 'Paraquat 200SL', quantity: '2-3 L/ha directed', farmId, batchId },
    { title: 'BEGIN PROPPING — support bunch-bearing plants (Month 8)', description: 'Start propping as bunches develop. Use bamboo poles 1.8-2.5m long at 45-degree angle on opposite side from bunch.', category: 'propping', dueDate: addMonths(pd, 8), priority: 'high', product: 'Bamboo poles or hardwood sticks', quantity: '1 pole per bunch-bearing plant', farmId, batchId },
    { title: 'Begin flowering monitoring and harvest countdown (Month 8)', description: 'Walk farm daily. When a bunch flower emerges, record the date. Count 90-120 days from flower emergence to harvest readiness.', category: 'inspection', dueDate: addMonths(pd, 8), priority: 'high', farmId, batchId },
    { title: 'Dry season management — mulching and monitoring (Month 9)', description: 'Dry season begins. No herbicide needed. Manual weed only. Mulch heavily. Monitor flowering and bunch development.', category: 'other', dueDate: addMonths(pd, 9), priority: 'medium', farmId, batchId },
    { title: 'Pre-harvest marketing — contact buyers (Month 10)', description: 'Contact Bodija Market dealers and restaurant/buka contacts on Olojuoro axis. Aim for 40% Bodija, 30% restaurant, 30% farm gate.', category: 'other', dueDate: addMonths(pd, 10), priority: 'high', farmId, batchId },
    { title: 'H4: Pre-harvest herbicide — clear farm for access (Month 11)', description: 'Apply Paraquat 200SL directed between rows. Clear access paths for harvest team and buyers.', category: 'herbicide', dueDate: addMonths(pd, 11), priority: 'medium', product: 'Paraquat 200SL', quantity: '2-3 L/ha directed', farmId, batchId },
    { title: 'FIRST HARVEST begins — stagger over 8-10 weeks', description: 'Begin harvesting bunches as they reach maturity (90-120 days from flower). Do NOT harvest all at once. Stagger over 8-10 weeks.', category: 'bunch_harvest', dueDate: addMonths(pd, 12), priority: 'critical', farmId, batchId },
    { title: 'F4: Ratoon fertilizer — NPK 15:15:15 (post each harvest)', description: 'Apply 150g NPK 15:15:15 per mat within 2-4 weeks of cutting each bunch. Feed each mat right after its harvest.', category: 'fertilizer', dueDate: addDays(addMonths(pd, 12), 21), priority: 'high', product: 'NPK 15:15:15', quantity: '150g per harvested mat (102kg total = 2 bags)', farmId, batchId },
    { title: 'CORM GOUGING — immediately after each bunch harvest', description: 'Gouge harvested mats IMMEDIATELY after bunch is cut: (1) Cut pseudostem to 30-45cm, (2) Expose corm crown, (3) Gouge central bud 5-8cm deep, (4) Pack hole with wood ash, (5) Mulch and keep moist.', category: 'gouging', dueDate: addDays(addMonths(pd, 12), 7), priority: 'critical', farmId, batchId },
  ];
}
